# Generated by Django 4.0.1 on 2023-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_students_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='classroom_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(default='default_image.jpg', upload_to='course_images/'),
        ),
    ]
