# Generated by Django 4.0.1 on 2023-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_remove_courses_classroom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='classroom_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
